### ISSUE TITLE
Does not support mode "servo"

### ISSUE THREAD

**Issue by ThadeuLuz** [nebrius/raspi-io#113]
I've been trying to run a very simple script for servos and can't figure out why I'm getting this error. Googled it exhaustively.

This is the script 
```
const five = require("johnny-five");
const Raspi = require("raspi-io");
const board = new five.Board({
  io: new Raspi()
});

board.on("ready", function() {
  const servo = new five.Servo("P1-16");
  servo.sweep();
});
```

This is what I get:

```
>> /home/pi/project/node_modules/raspi-io-core/dist/index.js:546
        throw new Error('Pin "' + pin + '" does not support mode "' + modeName + '"');
        ^

Error: Pin "4" does not support mode "servo"
    at RaspiIOCore.value (/home/pi/project/node_modules/raspi-io-core/dist/index.js:546:15)
    at RaspiIOCore.pinMode (/home/pi/project/node_modules/raspi-io-core/dist/index.js:512:21)
    at Servo.value (/home/pi/project/node_modules/johnny-five/lib/servo.js:58:19)
    at new Servo (/home/pi/project/node_modules/johnny-five/lib/servo.js:199:8)
    at Board.<anonymous> (/home/pi/project/src/s.js:8:17)
    at Board.emit (events.js:194:15)
    at Board.EventEmitter.emit (domain.js:441:20)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
```

Version `"raspi-io": "9.0.1"` and `"johnny-five": "^1.0.0"`.
Raspberry pi zero w.

Tried with and without software pwm. 

Thanks in advance.

**Comment by ThadeuLuz** [comment]
I'll try to figure this out and I'll re-open if needed.

**Comment by nebrius** [comment]
Glad you got it sorted out!
