### ISSUE TITLE
Johnny-five with 4x4 Keypad I2C Backpack does crash

### ISSUE THREAD

**Issue by AlexKutschera** [nebrius/raspi-io#137]
Hi there,
I would like to use the johnny-five Keypad Module with an I2C Nano Backpack, but unfortunately there seems to be an issue in the Raspberry Pi to Arduino Nano I2C Communication. I'm also using an I2C LCD which works fine and the Nano is listes when running i2cdetect. I get the following error when using the johhny-five example at [http://johnny-five.io/examples/keypad-4X4_I2C_NANO_BACKPACK/](http://johnny-five.io/examples/keypad-4X4_I2C_NANO_BACKPACK/)

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EREMOTEIO: remote I/O error, read
Emitted 'error' event on Board instance at:
    at J5IO.<anonymous> (/var/smart-treehouse/node_modules/johnny-five/lib/board.js:341:39)
    at J5IO.emit (events.js:315:20)
    at J5IO.EventEmitter.emit (domain.js:467:12)
    at readCB (/var/smart-treehouse/node_modules/j5-io/dist/managers/i2c.js:70:35)
    at /var/smart-treehouse/node_modules/raspi-i2c/dist/index.js:72:17
    at FSReqCallback.wrapper [as oncomplete] (fs.js:539:5) {
  errno: -121,
  code: 'EREMOTEIO',
  syscall: 'read'
}
```
this is my code including the I2C LCD initialization which works
```
const board = new five.Board({
    io: new RaspiIO()
});

board.on("ready", () => {
    DisplayManager.init(); // intitializes I2C LCD
    const keypad = new five.Keypad({
        controller: "4X4_I2C_NANO_BACKPACK"
    });
    ["change", "press", "hold", "release"].forEach(function (eventType) {
        keypad.on(eventType, function (event) {
            console.log("Event: %s, Target: %s", eventType, event.which);
        });
    });
    ...
})
```
I'm using johnny-five 2.0.0 and raspi-io 11.0.0 with node 14.16.0 on an Raspberry Pi 3 Model B Rev 1.2 running Raspbian GNU/Linux 10 (buster)

i2cdetect result: (27 is the LCD and 0d the Nano)
```
$ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- 0d -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- 27 -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**Comment by AlexKutschera** [comment]
found the problem: [https://github.com/rwaldron/johnny-five/issues/1723#issuecomment-790540913](https://github.com/rwaldron/johnny-five/issues/1723#issuecomment-790540913)
