### ISSUE TITLE
Error: pigpio error -1 in gpioInitialise

### ISSUE THREAD

**Issue by lbineau** [nebrius/raspi-io#141]
I've setup Johnny-Five on a Raspberry Pi Zero running on Raspbian and it works very well with an Arduino connected.
I'm trying to achieve the same without the Arduino by running Johnny-Five directly on the Pi thanks to RaspIO library
This is the simple code I'm trying to execute:

```node
var five = require("johnny-five");
var Raspi = require("raspi-io").RaspiIO;
var board = new five.Board({
  io: new Raspi()
});

board.on("ready", function() {
  var led = new five.Led("GPIO4");
  led.blink();
});
```

I've installed the library and got the following error after installation:

```bash
npm install raspi-io
npm run start

> chopper-robot@1.0.0 start
> node index.js

2023-08-21 22:56:08 initCheckPermitted:
+---------------------------------------------------------+
|Sorry, you don't have permission to run this program.    |
|Try running as root, e.g. precede the command with sudo. |
+---------------------------------------------------------+


/home/chopper/Sites/arduino-websocket/node_modules/pigpio/pigpio.js:17
    pigpio.gpioInitialise();
           ^

Error: pigpio error -1 in gpioInitialise
    at initializePigpio (/home/chopper/Sites/arduino-websocket/node_modules/pigpio/pigpio.js:17:12)
    at new Gpio (/home/chopper/Sites/arduino-websocket/node_modules/pigpio/pigpio.js:42:5)
    at new DigitalOutput (/home/chopper/Sites/arduino-websocket/node_modules/raspi-gpio/dist/index.js:70:24)
    at Object.createDigitalOutput (/home/chopper/Sites/arduino-websocket/node_modules/raspi-gpio/dist/index.js:129:16)
    at GPIOManager.setOutputMode (/home/chopper/Sites/arduino-websocket/node_modules/j5-io/dist/managers/gpio.js:43:36)
    at J5IO.pinMode (/home/chopper/Sites/arduino-websocket/node_modules/j5-io/dist/index.js:355:39)
    at new J5IO (/home/chopper/Sites/arduino-websocket/node_modules/j5-io/dist/index.js:208:22)
    at new RaspiIO (/home/chopper/Sites/arduino-websocket/node_modules/raspi-io/dist/index.js:122:12)
    at Object.<anonymous> (/home/chopper/Sites/arduino-websocket/robot/index.js:4:7)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)

Node.js v18.9.1
npm ERR! Lifecycle script `start` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: chopper-robot@1.0.0
npm ERR!   at location: /home/chopper/Sites/arduino-websocket/robot
```

In order to help to debug I'm putting more information
```bash
which node
/usr/local/bin/node

node -v
v18.9.1

npm -v
8.19.1
```

Any idea that might help?

**Comment by lbineau** [comment]
I get the issue, I'm an idiot...

Running
`sudo npm run start` with `"start": "node index.js"`
is different from running:
`npm run start` with `"start": "sudo node index.js"`
