### ISSUE TITLE
EIO ,i/o error

### ISSUE THREAD

**Issue by asit569** [nebrius/raspi-io#59]
I am getting this error and tried everything to fix but no success please resolve the issue

pi@raspberrypi:~ $ cd waterpi-node
pi@raspberrypi:~/waterpi-node $ sudo node index.js
1462815306876 Device(s) RaspberryPi-IO
1462815307277 Connected /dev/ttyACM0
1462815307365 Connected RaspberryPi-IO
connect
1462815311112 Board ID:  pi
1462815311114 Board ID:  uno
1462815311129 Repl Initialized
>> ready
Temperature: 33.00C, humidity: 45.00%
fs.js:613
    return binding.writeBuffer(fd, buffer, offset, length, position);
                   ^
Error: EIO, i/o error
    at Error (native)
    at Object.fs.writeSync (fs.js:613:20)
    at Bus.i2cWriteSync (/home/pi/waterpi-node/node_modules/raspi-io/node_modules/raspi-i2c/node_modules/i2c-bus/i2c-bus.js:340:13)
    at I2C.writeSync (/home/pi/waterpi-node/node_modules/raspi-io/node_modules/raspi-i2c/lib/index.js:332:34)
    at Raspi.i2cWrite (/home/pi/waterpi-node/node_modules/raspi-io/lib/index.js:559:19)
    at Expander.write (/home/pi/waterpi-node/node_modules/johnny-five/lib/lcd.js:49:11)
    at LCD.Controllers.PCF8574.initialize.value (/home/pi/waterpi-node/node_modules/johnny-five/lib/lcd.js:341:23)
    at new LCD (/home/pi/waterpi-node/node_modules/johnny-five/lib/lcd.js:734:10)
    at Boards.<anonymous> (/home/pi/waterpi-node/index.js:60:9)
    at Boards.emit (events.js:107:17)
    at Boards.<anonymous> (/home/pi/waterpi-node/node_modules/johnny-five/lib/board.js:1197:14)
    at process._tickDomainCallback (node.js:381:11)

**Comment by nebrius** [comment]
Closing in favor of https://github.com/rwaldron/johnny-five/issues/1128, let's discuss it there for now to keep the conversation focused.
