### ISSUE TITLE
Adafruit Ultimate GPS Issues

### ISSUE THREAD

**Issue by zsigix** [nebrius/raspi-io#67]
Hello,
 
I'm new to the Johnny-Five libraries, let alone the Raspi-IO library suite. I'm also trying to get the Adafruit Ultimate GPS HAT to work with my Raspberry Pi 2 (similar to issue #47 ). The code:
```javascript
var five = require("johnny-five");
var Raspi = require("raspi-io");
var board = new five.Board({
  io: new Raspi()
});

board.on("ready", function() {
  var gps = new five.GPS({
    breakout: "adafruitUltimateGPS",
    pins: { tx: "P1-8", rx: "P1-10" }
  });

  // If latitude, longitude, course or speed change log it
  gps.on("change", function() {
    console.log("position");
    console.log("  latitude   : ", this.latitude);
    console.log("  longitude  : ", this.longitude);
    console.log("--------------------------------------");
  });
});
```

And the output:
```
pi@raspberrypi ~/nodejs $ sudo node gps_test.js
1471744440488 Device(s) RaspberryPi-IO
1471744440598 Connected RaspberryPi-IO
1471744440628 Repl Initialized
>> /home/pi/nodejs/node_modules/johnny-five/lib/board.js:1008
  var requirements = controller.requirements && controller.requirements.value;
                               ^

TypeError: Cannot read property 'requirements' of undefined
    at GPS.Board.Controller (/home/pi/nodejs/node_modules/johnny-five/lib/board.js:1008:32)
    at new GPS (/home/pi/nodejs/node_modules/johnny-five/lib/gps.js:189:22)
    at Board.<anonymous> (/home/pi/nodejs/gps_test.js:8:13)
    at emitNone (events.js:85:20)
    at Board.emit (events.js:179:7)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Not sure what this means. Any idea what the issue may be?
 
Thanks in advance!
 
P.S.: I was confused by contributor rwaldron because my abbreviation of first initial/last name is the same (My first name is Ross).

**Comment by zsigix** [comment]
Sorry, wasn't referring to the right breakout. Checking the source confirmed that.
 
But now I get a new error, something about an invalid pin:
```
1471786664946 Device(s) RaspberryPi-IO
1471786665059 Connected RaspberryPi-IO
1471786665089 Repl Initialized
>> /home/pi/nodejs/node_modules/raspi-io/lib/index.js:366
        throw new Error('Pin "' + pin + '" does not support mode "' + mode + '"');
        ^

Error: Pin "P1-8" does not support mode "undefined"
    at Raspi.value (/home/pi/nodejs/node_modules/raspi-io/lib/index.js:366:15)
    at Raspi.pinMode (/home/pi/nodejs/node_modules/raspi-io/lib/index.js:348:21)
    at GPS.<anonymous> (/home/pi/nodejs/node_modules/johnny-five/lib/gps.js:269:15)
    at Array.forEach (native)
    at GPS.initialize (/home/pi/nodejs/node_modules/johnny-five/lib/gps.js:267:16)
    at new GPS (/home/pi/nodejs/node_modules/johnny-five/lib/gps.js:251:10)
    at Board.<anonymous> (/home/pi/nodejs/gps_test.js:8:13)
    at emitNone (events.js:85:20)
    at Board.emit (events.js:179:7)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```
 
Any idea what it could be? Thanks!

**Comment by zsigix** [comment]
Again, more fiddling, and it was magically fixed. Current code:
```javascript
var raspi = require("raspi-io");
var five = require("johnny-five");
var board = new five.Board({
  io: new raspi()
});

board.on("ready", function() {
  var gps = new five.GPS({
    breakout: "ADAFRUIT_ULTIMATE_GPS",
    pins: ['P1-8', 'P1-10']
  });

  // If latitude, longitude, course or speed change log it
  gps.on("change", function() {
    console.log("position");
    console.log("  latitude   : ", this.latitude);
    console.log("  longitude  : ", this.longitude);
    console.log("--------------------------------------");
  });
});
```

For future reference, if you're using the Adafruit Ultimate GPS with your Raspberry Pi, make sure your pins object in GPS initialization is an array (TX first, RX second). The Johnny-Five example with the rx/tx object didn't pan out for me.
 
Closing issue.
